dvrk:
  SUJ:
    SUJ_PSM1_J0_controller:
      p: 50000
      i: 0
      d: 10

    SUJ_PSM1_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM1_J4_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J0_controller:
      p: 3000
      i: 0
      d: 10

    SUJ_ECM_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_ECM_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM2_J4_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J0_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J1_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J2_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J3_controller:
      p: 2000
      i: 0
      d: 10

    SUJ_PSM3_J4_controller:
      p: 2000
      i: 0
      d: 10
  PSM1:
    rev_joint_controller:
      p: 200
      i: 0
      d: 10
    outer_yaw_joint_controller:
      p: 20
      i: 0
      d: 10
    outer_pitch_joint_1_controller:
      p: 600
      i: 0
      d: 0
    outer_insertion_joint_controller:
      p: 40
      i: 0
      d: 1
  PSM2:
    rev_joint_controller:
      p: 200
      i: 0
      d: 10
    outer_yaw_joint_controller:
      p: 20
      i: 0
      d: 10
    outer_pitch_joint_1_controller:
      p: 600
      i: 0
      d: 0
    outer_insertion_joint_controller:
      p: 40
      i: 0
      d: 1
  PSM3:
    rev_joint_controller:
      p: 200
      i: 0
      d: 10
    outer_yaw_joint_controller:
      p: 20
      i: 0
      d: 10
    outer_pitch_joint_1_controller:
      p: 600
      i: 0
      d: 0
    outer_insertion_joint_controller:
      p: 40
      i: 0
      d: 1
  ecm:
    yaw_joint_controller:
      p: 20
      i: 0
      d: 10
    pitch_front_joint_controller:
      p: 500
      i: 0
      d: 0
    main_insertion_joint_controller:
      p: 50
      i: 0
      d: 0
